{{- if not .Values.backend.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.database.secretName }}
  labels:
    {{- include "gitops-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
stringData:
  {{- $dbHost := .Values.backend.database.host | default (printf "%s-postgres" (include "gitops-demo.fullname" .)) }}
  PGHOST: {{ $dbHost | quote }}
  PGPORT: {{ .Values.backend.database.port | quote }}
  PGDATABASE: {{ .Values.backend.database.name | quote }}
  PGUSER: {{ .Values.backend.database.user | quote }}
  PGPASSWORD: {{ .Values.backend.database.password | quote }}
  DATABASE_URL: postgres://{{ .Values.backend.database.user }}:{{ .Values.backend.database.password }}@{{ $dbHost }}:{{ .Values.backend.database.port }}/{{ .Values.backend.database.name }}
{{- end }}
