apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitops-demo.fullname" . }}-backend
  labels:
    {{- include "gitops-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gitops-demo.fullname" . }}-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gitops-demo.fullname" . }}-backend
        app.kubernetes.io/component: backend
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            {{- $dbSecret := .Values.backend.database.existingSecret | default .Values.backend.database.secretName }}
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: {{ $dbSecret }}
                  key: PGHOST
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: {{ $dbSecret }}
                  key: PGPORT
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ $dbSecret }}
                  key: PGDATABASE
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ $dbSecret }}
                  key: PGUSER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $dbSecret }}
                  key: PGPASSWORD
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ $dbSecret }}
                  key: DATABASE_URL
            {{- with .Values.backend.env.extra }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
