version: '3.9'

services:
  frontend:
    build: ./apps/frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    build: ./apps/backend
    environment:
      PGHOST: db
      PGUSER: appuser
      PGPASSWORD: applocal
      PGDATABASE: appdb
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: applocal
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
