nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []
frontend:
  replicaCount: 2
  image:
    repository: ghcr.io/vrityacoderishi/gitops-demo-frontend
    tag: 257fb0d5b01ca2b2d8f7e4ba80818f3706233b97
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
backend:
  replicaCount: 2
  image:
    repository: ghcr.io/vrityacoderishi/gitops-demo-backend
    tag: 257fb0d5b01ca2b2d8f7e4ba80818f3706233b97
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  env:
    extra: []
  database:
    host: ""
    port: 5432
    name: appdb
    user: appuser
    password: applocal
    existingSecret: ""
    secretName: gitops-demo-backend-db
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
postgres:
  enabled: true
  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
  storage:
    size: 1Gi
    className: ""
    subPath: "pgdata"
  service:
    port: 5432
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: demo.example.com
      frontendPath: /
      backendPath: /api
  tls: []
