name: build-and-gitops

on:
  push:
    branches:
      - main
    paths:
      - "apps/**"
      - "helm/**"
      - ".github/workflows/gitops.yaml"
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install backend dependencies
        run: npm ci
        working-directory: apps/backend
      - name: Helm lint
        uses: azure/setup-helm@v4
      - name: Run helm lint
        run: helm lint helm/gitops-demo

  build-and-push:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prepare image coordinates
        id: image_meta
        run: |
          owner=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          echo "owner=$owner" >> "$GITHUB_OUTPUT"
          echo "frontend=${{ env.REGISTRY }}/$owner/gitops-demo-frontend" >> "$GITHUB_OUTPUT"
          echo "backend=${{ env.REGISTRY }}/$owner/gitops-demo-backend" >> "$GITHUB_OUTPUT"
      - uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push frontend image
        id: build-frontend
        uses: docker/build-push-action@v5
        with:
          context: apps/frontend
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ steps.image_meta.outputs.frontend }}:${{ github.sha }}
            ${{ steps.image_meta.outputs.frontend }}:latest
      - name: Build and push backend image
        id: build-backend
        uses: docker/build-push-action@v5
        with:
          context: apps/backend
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ steps.image_meta.outputs.backend }}:${{ github.sha }}
            ${{ steps.image_meta.outputs.backend }}:latest
      - name: Install yq
        if: github.ref == 'refs/heads/main'
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.2/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
      - name: Update Helm values with new image tags
        if: github.ref == 'refs/heads/main' && github.actor != 'github-actions[bot]'
        env:
          GIT_SHA: ${{ github.sha }}
        run: |
          yq eval ".frontend.image.repository = \"${{ steps.image_meta.outputs.frontend }}\"" -i helm/gitops-demo/values.yaml
          yq eval ".frontend.image.tag = \"${GIT_SHA}\"" -i helm/gitops-demo/values.yaml
          yq eval ".backend.image.repository = \"${{ steps.image_meta.outputs.backend }}\"" -i helm/gitops-demo/values.yaml
          yq eval ".backend.image.tag = \"${GIT_SHA}\"" -i helm/gitops-demo/values.yaml
      - name: Commit Helm value updates
        if: github.ref == 'refs/heads/main' && github.actor != 'github-actions[bot]'
        env:
          GIT_SHA: ${{ github.sha }}
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "ci: update image tags to ${GIT_SHA}"
          branch="${GITHUB_REF##*/}"
          git push origin "HEAD:${branch}"
